config/routes.rb
Rails.application.routes.draw do
  root  'application_staffs#index'
  resources :application_staffs, path: 'staffs'
  resources :hirers
  resources :settings
  resources :regions
  resources :settlements

  match '/getStaff',  to: 'application_staffs#getStaff', via: [:get,:post]
  match '/getSettlements',  to: 'settlements#getSettlements', via: [:get,:post]

  resources :positions, path: 'positions'
  resources :managers
  resources :spheres
  resources :nationalities
  resources :stop_sheet_statuses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_staff.rb
class ApplicationStaff < ApplicationRecord
  belongs_to :nationality, optional: true
  belongs_to :emp_type, optional: true
  belongs_to :etnicity, optional: true
  belongs_to :status_interview, optional: true
  belongs_to :status_treatment, optional: true
  belongs_to :stop_sheet_status, optional: true
  belongs_to :residence_document, optional: true
  belongs_to :manager, optional: true
  belongs_to :desired_region, class_name: Region
  belongs_to :patent_region, class_name: Region,optional: true

  has_many :app_staff_pos_positions
  has_many :possible_positions, through: :app_staff_pos_positions
  has_many :settlements

  enum sex: { man: 0, woman: 1 }


  mount_uploader :avatar, AvatarUploader

  #validates_presence_of :surname, :name, :patronymic, :message => "Заполните обязательные поля"

  def formatted_name
    "#{surname}  #{name} #{patronymic}"
  end
end

app/models/emp_type.rb
class EmpType < ApplicationRecord
  has_many :application_staffs
end

app/models/etnicity.rb
class Etnicity < ApplicationRecord
  has_many :application_staffs
end

app/models/hirer.rb
class Hirer < ApplicationRecord

  belongs_to :sphere, optional: true
  has_many :settlements

end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :application_staffs
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  has_many :application_staffs
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :settlements
end

app/models/possible_position.rb
class PossiblePosition < ApplicationRecord
  has_many :app_staff_pos_positions
  has_many :application_staffs, through: :app_staff_pos_positions
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :application_staffs
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  include EnumHelper
  enum payment_type: { cash: 0, cashless: 1 }

  belongs_to :hirer, optional: true
  belongs_to :position, optional: true
  belongs_to :application_staff, optional: true

  def formatted_shift
    shift.strftime("%H:%M") if shift?
  end


end

app/models/sphere.rb
class Sphere < ApplicationRecord
  has_many :hirers
end

app/models/status_interview.rb
class StatusInterview < ApplicationRecord
  has_many :application_staffs
end

app/models/status_treatment.rb
class StatusTreatment < ApplicationRecord
  has_many :application_staffs
end

app/models/stop_sheet_status.rb
class StopSheetStatus < ApplicationRecord
  has_many :application_staffs
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  def index
    @positions = Position.all
  end

  # GET /positions/1
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  def create
    @position = Position.new(position_params)

    if @position.save
      redirect_to @position, notice: 'Position was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /positions/1
  def update
    if @position.update(position_params)
      redirect_to positions_url, notice: 'Position was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /positions/1
  def destroy
    @position.destroy
    redirect_to positions_url, notice: 'Position was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def position_params
      params.require(:position).permit(:id, :display_name)
    end
end

app/helpers/errors_helper.rb
module ErrorsHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: "panel panel-danger") do
        concat(content_tag(:div, class: "panel-heading") do
          concat(content_tag(:h4, class: "panel-title") do
            concat "#{pluralize(object.errors.count,"error")} prohibited this #{object.class.name.downcase} from being saved"
          end)
        end)
        concat(content_tag(:div, class: "panel-body") do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li,msg)
            end
          end)
      end)
    end
    end
  end
end

app/helpers/hirers_helper.rb
module HirersHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/spheres_helper.rb
module SpheresHelper
end

app/views/positions/_form.html.slim
.container
  = form_for @position, html: {class: "edit_post"} do |f|
    - if @position.errors.any?
      #error_explanation
        h2 = "#{pluralize(@position.errors.count, "error")} prohibited this position from being saved:"
        ul
          - @position.errors.full_messages.each do |message|
            li = message

    .row
    br
      .col-md-10
        .form.form-horizontal
          .form-group
            = f.label :display_name, "Вакансия", class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :display_name, class: 'form-control'

        .actions = f.submit class: 'btn btn-primary move-right'

app/views/positions/edit.html.slim
h1 Редактирование вакансии

== render 'form'

app/views/positions/index.html.slim
h1 Список вакансий
= link_to 'Добавить вакансию', new_position_path
table.table
  thead
    tr
      th
      th
      th

  tbody
    - @positions.each do |position|
      tr
        td =  position.display_name
        td = link_to 'Изменить', edit_position_path(position)
        td = link_to 'Удалить', position, data: { confirm: 'Are you sure?' }, method: :delete

br

app/views/positions/new.html.slim
h1 Новая вакансия

== render 'form'

app/views/positions/show.html.slim
p#notice = notice


= link_to 'Edit', edit_position_path(@position)
'  |
= link_to 'Back', positions_path