config/routes.rb
Rails.application.routes.draw do
  root  'application_staffs#index'
  resources :application_staffs, path: 'staffs'
  resources :hirers
  resources :settings
  resources :regions
  resources :settlements

  match '/getStaff',  to: 'application_staffs#getStaff', via: [:get,:post]
  match '/getSettlements',  to: 'settlements#getSettlements', via: [:get,:post]

  resources :positions, path: 'positions'
  resources :managers
  resources :spheres
  resources :nationalities
  resources :stop_sheet_statuses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_staff.rb
class ApplicationStaff < ApplicationRecord
  belongs_to :nationality, optional: true
  belongs_to :emp_type, optional: true
  belongs_to :etnicity, optional: true
  belongs_to :status_interview, optional: true
  belongs_to :status_treatment, optional: true
  belongs_to :stop_sheet_status, optional: true
  belongs_to :residence_document, optional: true
  belongs_to :manager, optional: true
  belongs_to :desired_region, class_name: Region
  belongs_to :patent_region, class_name: Region,optional: true

  has_many :app_staff_pos_positions
  has_many :possible_positions, through: :app_staff_pos_positions
  has_many :settlements

  enum sex: { man: 0, woman: 1 }


  mount_uploader :avatar, AvatarUploader

  #validates_presence_of :surname, :name, :patronymic, :message => "Заполните обязательные поля"

  def formatted_name
    "#{surname}  #{name} #{patronymic}"
  end
end

app/models/emp_type.rb
class EmpType < ApplicationRecord
  has_many :application_staffs
end

app/models/etnicity.rb
class Etnicity < ApplicationRecord
  has_many :application_staffs
end

app/models/hirer.rb
class Hirer < ApplicationRecord

  belongs_to :sphere, optional: true
  has_many :settlements

end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :application_staffs
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  has_many :application_staffs
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :settlements
end

app/models/possible_position.rb
class PossiblePosition < ApplicationRecord
  has_many :app_staff_pos_positions
  has_many :application_staffs, through: :app_staff_pos_positions
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :application_staffs
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  include EnumHelper
  enum payment_type: { cash: 0, cashless: 1 }

  belongs_to :hirer, optional: true
  belongs_to :position, optional: true
  belongs_to :application_staff, optional: true

  def formatted_shift
    shift.strftime("%H:%M") if shift?
  end


end

app/models/sphere.rb
class Sphere < ApplicationRecord
  has_many :hirers
end

app/models/status_interview.rb
class StatusInterview < ApplicationRecord
  has_many :application_staffs
end

app/models/status_treatment.rb
class StatusTreatment < ApplicationRecord
  has_many :application_staffs
end

app/models/stop_sheet_status.rb
class StopSheetStatus < ApplicationRecord
  has_many :application_staffs
end

app/controllers/spheres_controller.rb
class SpheresController < ApplicationController
  before_action :set_sphere, only: [:show, :edit, :update, :destroy]

  # GET /spheres
  def index
    @spheres = Sphere.all
  end

  # GET /spheres/1
  def show
  end

  # GET /spheres/new
  def new
    @sphere = Sphere.new
  end

  # GET /spheres/1/edit
  def edit
    @sphere = Sphere.find(params[:id])
  end

  # POST /spheres
  def create
    @sphere = Sphere.new(sphere_params)

    if @sphere.save
      redirect_to spheres_url, notice: 'Sphere was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /spheres/1
  def update
    if @sphere.update(sphere_params)
      redirect_to spheres_url, notice: 'Sphere was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /spheres/1
  def destroy
    @sphere.destroy
    redirect_to spheres_url, notice: 'Sphere was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sphere
      @sphere = Sphere.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sphere_params
      params.require(:sphere).permit(:id, :display_name);
    end
end

app/helpers/errors_helper.rb
module ErrorsHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: "panel panel-danger") do
        concat(content_tag(:div, class: "panel-heading") do
          concat(content_tag(:h4, class: "panel-title") do
            concat "#{pluralize(object.errors.count,"error")} prohibited this #{object.class.name.downcase} from being saved"
          end)
        end)
        concat(content_tag(:div, class: "panel-body") do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li,msg)
            end
          end)
      end)
    end
    end
  end
end

app/helpers/hirers_helper.rb
module HirersHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/spheres_helper.rb
module SpheresHelper
end

app/views/spheres/_form.html.slim
.container
  = form_for @sphere, html: {class: "edit_post"} do |f|
    - if @sphere.errors.any?
      #error_explanation
        h2 = "#{pluralize(@sphere.errors.count, "error")} prohibited this sphere from being saved:"
        ul
          - @sphere.errors.full_messages.each do |message|
            li = message

    .row
    br
      .col-md-10
        .form.form-horizontal
          .form-group
            = f.label :display_name, "Вакансия", class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :display_name, class: 'form-control'

        .actions = f.submit class: 'btn btn-primary move-right'

app/views/spheres/edit.html.slim
h1 Редактирование сферы деятельности

== render 'form'

app/views/spheres/index.html.slim
h1 Список регионов
= link_to 'Новая сфера деятельности', new_sphere_path
table.table
  thead
    tr
      th Регион
      th Изменить
      th Удалить
  tbody
    - @spheres.each do |sphere|
      tr
        td = sphere.display_name
        td = link_to 'Edit', edit_sphere_path(sphere)
        td = link_to 'Destroy', sphere, data: {confirm: 'Are you sure?'}, method: :delete

br

app/views/spheres/new.html.slim
h1 New sphere

== render 'form'

br
br
br
= link_to 'Back', spheres_path

app/views/spheres/show.html.slim
p#notice = notice


= link_to 'Edit', edit_sphere_path(@sphere)
'  |
= link_to 'Back', spheres_path