config/routes.rb
Rails.application.routes.draw do
  root  'application_staffs#index'
  resources :application_staffs, path: 'staffs'
  resources :hirers
  resources :settings
  resources :regions
  resources :settlements

  match '/getStaff',  to: 'application_staffs#getStaff', via: [:get,:post]
  match '/getSettlements',  to: 'settlements#getSettlements', via: [:get,:post]

  resources :positions, path: 'positions'
  resources :managers
  resources :spheres
  resources :nationalities
  resources :stop_sheet_statuses
end

app/models/application_staff.rb
class ApplicationStaff < ApplicationRecord
  belongs_to :nationality, optional: true
  belongs_to :emp_type, optional: true
  belongs_to :etnicity, optional: true
  belongs_to :status_interview, optional: true
  belongs_to :status_treatment, optional: true
  belongs_to :stop_sheet_status, optional: true
  belongs_to :residence_document, optional: true
  belongs_to :manager, optional: true
  belongs_to :desired_region, class_name: Region
  belongs_to :patent_region, class_name: Region,optional: true

  has_many :app_staff_pos_positions
  has_many :possible_positions, through: :app_staff_pos_positions
  has_many :settlements

  enum sex: { man: 0, woman: 1 }


  mount_uploader :avatar, AvatarUploader

  #validates_presence_of :surname, :name, :patronymic, :message => "Заполните обязательные поля"

  def formatted_name
    "#{surname}  #{name} #{patronymic}"
  end
end

app/models/emp_type.rb
class EmpType < ApplicationRecord
  has_many :application_staffs
end

app/models/etnicity.rb
class Etnicity < ApplicationRecord
  has_many :application_staffs
end

app/models/hirer.rb
class Hirer < ApplicationRecord

  belongs_to :sphere, optional: true
  has_many :settlements

end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :application_staffs
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  has_many :application_staffs
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :settlements
end

app/models/possible_position.rb
class PossiblePosition < ApplicationRecord
  has_many :app_staff_pos_positions
  has_many :application_staffs, through: :app_staff_pos_positions
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :application_staffs
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  include EnumHelper
  enum payment_type: { cash: 0, cashless: 1 }

  belongs_to :hirer, optional: true
  belongs_to :position, optional: true
  belongs_to :application_staff, optional: true

  def formatted_shift
    shift.strftime("%H:%M") if shift?
  end


end

app/models/sphere.rb
class Sphere < ApplicationRecord
  has_many :hirers
end

app/models/status_interview.rb
class StatusInterview < ApplicationRecord
  has_many :application_staffs
end

app/models/status_treatment.rb
class StatusTreatment < ApplicationRecord
  has_many :application_staffs
end

app/controllers/stop_sheet_statuses_controller.rb
class StopSheetStatusesController < ApplicationController
  before_action :set_stop_sheet_status, only: [:show, :edit, :update, :destroy]

  # GET /stop_sheet_statuses
  def index
    @stop_sheet_statuses = StopSheetStatus.all
  end

  # GET /stop_sheet_statuses/1
  def show
  end

  # GET /stop_sheet_statuses/new
  def new
    @stop_sheet_status = StopSheetStatus.new
  end

  # GET /stop_sheet_statuses/1/edit
  def edit
    @stop_sheet_status = StopSheetStatus.find(params[:id])
  end

  # POST /stop_sheet_statuses
  def create
    @stop_sheet_status = StopSheetStatus.new(stop_sheet_status_params)

    if @stop_sheet_status.save
      redirect_to @stop_sheet_status, notice: 'Stop sheet status was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stop_sheet_statuses/1
  def update
    if @stop_sheet_status.update(stop_sheet_status_params)
      redirect_to stop_sheet_statuses_url, notice: 'Stop sheet status was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stop_sheet_statuses/1
  def destroy
    @stop_sheet_status.destroy
    redirect_to stop_sheet_statuses_url, notice: 'Stop sheet status was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop_sheet_status
      @stop_sheet_status = StopSheetStatus.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def stop_sheet_status_params
      params.require(:stop_sheet_status).permit(:id, :display_name)
    end
end

app/helpers/errors_helper.rb
module ErrorsHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: "panel panel-danger") do
        concat(content_tag(:div, class: "panel-heading") do
          concat(content_tag(:h4, class: "panel-title") do
            concat "#{pluralize(object.errors.count,"error")} prohibited this #{object.class.name.downcase} from being saved"
          end)
        end)
        concat(content_tag(:div, class: "panel-body") do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li,msg)
            end
          end)
      end)
    end
    end
  end
end

app/helpers/hirers_helper.rb
module HirersHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/spheres_helper.rb
module SpheresHelper
end

app/helpers/stop_sheet_statuses_helper.rb
module StopSheetStatusesHelper
end

app/views/stop_sheet_statuses/_form.html.slim
.container
  = form_for @stop_sheet_status, html: {class: "edit_post"} do |f|
    - if @stop_sheet_status.errors.any?
      #error_explanation
        h2 = "#{pluralize(@stop_sheet_status.errors.count, "error")} prohibited this stop_sheet_status from being saved:"
        ul
          - @stop_sheet_status.errors.full_messages.each do |message|
            li = message

    .row
    br
      .col-md-10
        .form.form-horizontal
          .form-group
            = f.label :display_name, "Статус", class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :display_name, class: 'form-control'

        .actions = f.submit class: 'btn btn-primary move-right'

app/views/stop_sheet_statuses/edit.html.slim
h1 Редактирование статуса

== render 'form'

app/views/stop_sheet_statuses/index.html.slim
h1 Список статусов
= link_to 'Новая статус', new_stop_sheet_status_path
table.table
  thead
    tr
      th Статус
      th Изменить
      th Удалить
  tbody
    - @stop_sheet_statuses.each do |stop_sheet_status|
      tr
        td = stop_sheet_status.display_name
        td = link_to 'Edit', edit_stop_sheet_status_path(stop_sheet_status)
        td = link_to 'Destroy', stop_sheet_status, data: {confirm: 'Are you sure?'}, method: :delete

br

app/views/stop_sheet_statuses/new.html.slim
h1 New stop_sheet_status

== render 'form'

= link_to 'Back', stop_sheet_statuses_path

app/views/stop_sheet_statuses/show.html.slim
p#notice = notice


= link_to 'Edit', edit_stop_sheet_status_path(@stop_sheet_status)
'  |
= link_to 'Back', stop_sheet_statuses_path